# Generated by Django 2.1.7 on 2019-03-31 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher_Registration_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_image', models.ImageField(upload_to='teacher_image')),
                ('teacher_name', models.CharField(max_length=200)),
                ('class_teacher_of', models.CharField(max_length=2)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
