# Generated by Django 2.1.7 on 2019-04-07 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addingassignment',
            name='adding_time',
            field=models.TimeField(auto_now=datetime.datetime(2019, 4, 7, 14, 20, 21, 223531)),
        ),
    ]
