# Generated by Django 2.1.7 on 2019-04-01 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_trymodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher_registration_model',
            name='teacher_image',
        ),
    ]
