# Generated by Django 2.1.7 on 2019-04-07 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20190407_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='addingassignment',
            name='teacher_message',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addingassignment',
            name='adding_time',
            field=models.TimeField(auto_now=datetime.datetime(2019, 4, 7, 14, 31, 48, 230314)),
        ),
        migrations.AlterField(
            model_name='addingassignment',
            name='picture_of_assignment',
            field=models.ImageField(upload_to='assignment'),
        ),
    ]
