# Generated by Django 2.1.7 on 2019-04-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_remove_teacher_registration_model_teacher_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher_registration_model',
            name='teacher_name',
        ),
        migrations.AddField(
            model_name='teacher_registration_model',
            name='first_name',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher_registration_model',
            name='last_name',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher_registration_model',
            name='username',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
    ]
