# Generated by Django 2.1.7 on 2019-04-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_auto_20190401_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherregistration',
            name='email',
            field=models.EmailField(default=True, max_length=254),
        ),
    ]
