# Generated by Django 2.1.7 on 2019-04-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_teacherregistration_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherregistration',
            name='class_teacher_of',
            field=models.CharField(max_length=5),
        ),
    ]
