# Generated by Django 2.1.7 on 2019-04-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_auto_20190401_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherregistration',
            name='phone_number',
            field=models.IntegerField(default=True, max_length=10),
            preserve_default=False,
        ),
    ]
