# Generated by Django 2.1.7 on 2019-04-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_teacherregistration_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherregistration',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
