# Generated by Django 2.1.7 on 2019-04-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('student_name', models.CharField(max_length=200)),
                ('student_class', models.IntegerField()),
                ('student_id', models.IntegerField()),
                ('student_email', models.EmailField(max_length=254)),
                ('student_password', models.CharField(max_length=100)),
            ],
        ),
    ]
