# Generated by Django 2.1.7 on 2019-04-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_studentregistration_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentregistration',
            name='student_name',
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='first_name',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='last_name',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
    ]
