# Generated by Django 2.1.7 on 2019-04-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20190401_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='phone_number',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
    ]
